title: Optivem Northwind (C#)
description: .NET Core 2 REST API for the Northwind application
google_analytics: UA-63306472-4
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions