version: 1.0.{build}
image: Visual Studio 2017

services:
  - mssql2017

before_build:
- cmd: dotnet restore
- cmd: nuget restore
- cmd: appveyor.ps1

build:
  verbosity: minimal
  project: Optivem.Northwind.sln